import{a as w,i as a,S as C}from"./assets/vendor-BBSqv8W6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const S="49548683-ee808159962119513bc31ef98",v="https://pixabay.com/api/";async function f(o,t){try{const s=await w.get(v,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",page:t,per_page:15,safesearch:!0}});return s.data.hits.length===0&&a.error({message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#B51B1B",position:"topRight"}),s.data}catch{return a.error({message:"An error occurred while fetching images. Please try again later.",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#B51B1B",position:"topRight"}),{hits:[],totalHits:0}}}const M=new C(".gallery a",{captionsData:"alt"}),h=document.querySelector(".gallery"),y=document.querySelector(".loader"),F=document.querySelector(".btnMore");function P(){h.innerHTML=""}function p(o){const t=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:r,views:n,comments:L,downloads:B})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${c}" >
        <img src="${s}" alt="${e}">
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${n}</p>
        <p><b>Comments:</b> ${L}</p>
        <p><b>Downloads:</b> ${B}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function q(){var t;const o=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:o*3,behavior:"smooth"})}function d(){y.classList.add("loader")}function m(){y.classList.remove("loader")}function b(){F.classList.add("btnMore")}function g(){F.classList.remove("btnMore")}const x=document.querySelector(".form"),i=document.querySelector(".btnMore");let u="",l=1;m();i.textContent="";g();x.addEventListener("submit",async o=>{if(o.preventDefault(),u=o.target.elements["search-text"].value.trim(),!u){a.error({message:"Please enter a search term!",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#B51B1B",position:"topRight"});return}l=1,d(),g(),P();try{const{hits:t,totalHits:s}=await f(u,l);p(t),t.length>0&&s>15?(i.textContent="Load more",b()):(g(),d())}catch{a.error({message:"Something went wrong. Please try again."})}finally{m()}});i.addEventListener("click",async()=>{i.textContent="",g(),d(),l+=1;try{const{hits:o,totalHits:t}=await f(u,l);p(o),d(),l*15<t?(i.textContent="Load more",b()):a.info({message:"We're sorry, but you've reached the end of search results.",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#1B6CB5",position:"topRight"}),q()}catch{a.error({message:"Something went wrong. Please try again."}),m()}finally{m()}});
//# sourceMappingURL=index.js.map
