import{a as B,i as a,S as w}from"./assets/vendor-BBSqv8W6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const C="49548683-ee808159962119513bc31ef98",S="https://pixabay.com/api/";async function F(o,t){try{return(await B.get(S,{params:{key:C,q:o,image_type:"photo",orientation:"horizontal",page:t,per_page:15,safesearch:!0}})).data}catch{return a.error({message:"An error occurred while fetching images. Please try again later.",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#B51B1B",position:"topRight"}),{hits:[],totalHits:0}}}const v=new w(".gallery a",{captionsData:"alt"}),m=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".btnMore");function P(){m.innerHTML=""}function f(o){const t=o.map(({webformatURL:s,largeImageURL:l,tags:e,likes:r,views:n,comments:b,downloads:L})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${l}" >
        <img src="${s}" alt="${e}">
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${n}</p>
        <p><b>Comments:</b> ${b}</p>
        <p><b>Downloads:</b> ${L}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",t),v.refresh()}function q(){var t;const o=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:o*2,behavior:"smooth"})}function y(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}function u(){h.classList.add("hidden")}function p(){h.classList.remove("hidden")}const M=document.querySelector(".form"),$=document.querySelector(".btnMore");let c="",i=1;d();u();M.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),!c){a.error({message:"Please enter a search term!",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#B51B1B",position:"topRight"});return}i=1,y(),u(),P();try{const{hits:t,totalHits:s}=await F(c,i);if(s===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#B51B1B",position:"topRight"});return}f(t),s>i*15?p():a.info({message:"We're sorry, but you've reached the end of search results.",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#1B6CB5",position:"topRight"})}catch{a.error({message:"Something went wrong. Please try again."})}finally{d()}});$.addEventListener("click",async()=>{u(),y(),i+=1;try{const{hits:o,totalHits:t}=await F(c,i);f(o),i*15<t?p():a.info({message:"We're sorry, but you've reached the end of search results.",titleColor:"#FFFFFF",messageColor:"#FFFFFF",color:"#1B6CB5",position:"topRight"}),q()}catch{a.error({message:"Something went wrong. Please try again."})}finally{d()}});
//# sourceMappingURL=index.js.map
